In [88]:
import pandas as pd

In [89]:
data = {'Name': ['João', 'Maria', 'Pedro', 'Anna'], 'Age' :[25,30,35,20]}
df = pd.DataFrame(data)
df

    Name  Age
0   João   25
1  Maria   30
2  Pedro   35
3   Anna   20

In [90]:
df = pd.DataFrame(data, index = ['Rank1', 'Rank2', 'Rank3', 'Rank4'])
df

        Name  Age
Rank1   João   25
Rank2  Maria   30
Rank3  Pedro   35
Rank4   Anna   20

In [91]:
data = [{'a': 1, 'b': 2}, {'a': 1, 'b': 2, 'c': 3}]
df = pd.DataFrame(data)
df
#Vai dar erro (NaN), porque uma parte tem 2 elementos e a outra tem 3

   a  b    c
0  1  2  NaN
1  1  2  3.0

In [92]:
df1 = pd.DataFrame(data, index =['first', 'second'], columns= ['a', 'b'])

df2= pd.DataFrame(data, index =['first', 'second'], columns= ['a', 'b1'])

print (df1)
print (df2)

        a  b
first   1  2
second  1  2
        a  b1
first   1 NaN
second  1 NaN

In [93]:
dados = {'one' : pd.Series([1,2,3], index = ['a', 'b', 'c']), 'two' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])}
df = pd.DataFrame(dados)
df

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [94]:
print ("Adicionando uma nova coluna passando como Series")
df['three'] = pd.Series([10,20,30], index = ['a', 'b', 'c'])
print (df)

print ("Adicionando uma nova coluna usando as colunas existentes no DataFrame:")
df['four']=df['one']+df['three']

print (df)

Adicionando uma nova coluna passando como Series
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
Adicionando uma nova coluna usando as colunas existentes no DataFrame:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

In [96]:
df = pd.DataFrame([[1,2], [3,4]], columns = ['a','b'])
df2 = pd.DataFrame([[5,6], [7,8]], columns = ['a','b'])
df = pd.concat([df, df2])

#Excluindo as linhas com rótulo 0
df = df.drop(0)

print (df)

   a  b
1  3  4
1  7  8