In [1]:
import pandas as pd

In [ ]:
#Questão 1
data1 = [{'leonardo':6, 'nicolas':5, 'adriano':8, 'gustavo':10}]
df1 = pd.DataFrame(data1)
df1

   leonardo  nicolas  adriano  gustavo
0         6        5        8       10

In [ ]:
#Questão 2
data2 = [{'nome': 'Anna', 'cargo': 'analista'},{'nome':'Leonardo', 'cargo': 'Gerente', 'bonus': 5420}]
df2 = pd.DataFrame(data2)
df2

#Ana ficou com bonus = a "NaN", porque "bonus" só foi definido depois.

       nome     cargo   bonus
0      Anna  analista     NaN
1  Leonardo   Gerente  5420.0

In [ ]:
#Questão 3 

# Primeira Series contendo os nomes de três produtos
nomes_produtos = pd.Series(['Teclado', 'Mouse', 'Monitor'], index=['p1', 'p2', 'p3'])

# Segunda Series contendo os preços dos produtos
precos_produtos = pd.Series([150.00, 80.00, 950.00], index=['p1', 'p2', 'p3'])

# Unindo as Series em um DataFrame
df_produtos = pd.DataFrame({
    'Produto': nomes_produtos,
    'Preço (R$)': precos_produtos
})

# Exibindo o DataFrame resultante
display(df_produtos)

    Produto  Preço (R$)
p1  Teclado       150.0
p2    Mouse        80.0
p3  Monitor       950.0

In [ ]:
# Questão 4

# Criando dados fictícios e o DataFrame inicial
dados = {
    'Sede A': [15000.50, 22000.00, 18500.25],
    'Sede B': [12000.00, 19500.75, 14200.00]
         }
df_vendas = pd.DataFrame(dados)

# Exibindo o DataFrame original
print("DataFrame Original:")
display(df_vendas)

# Criando uma nova coluna 'Total Vendas' com a soma das duas sedes
df_vendas['Total Vendas'] = df_vendas['Sede A'] + df_vendas['Sede B']

# Adicionando uma coluna 'Imposto' calculada como 10% do valor da 'Sede A'
df_vendas['Imposto'] = df_vendas['Sede A'] * 0.10

# Exibindo o DataFrame após adicionar as novas colunas
print("\nDataFrame com 'Total Vendas' e 'Imposto':")
display(df_vendas)

DataFrame Original:

     Sede A    Sede B
0  15000.50  12000.00
1  22000.00  19500.75
2  18500.25  14200.00

DataFrame com 'Total Vendas' e 'Imposto':

     Sede A    Sede B  Total Vendas   Imposto
0  15000.50  12000.00      27000.50  1500.050
1  22000.00  19500.75      41500.75  2200.000
2  18500.25  14200.00      32700.25  1850.025

In [ ]:
# Questão 5

# Criando um DataFrame de clientes fictício
dados_clientes = {
    'Nome': ['Ana', 'Carlos', 'Beatriz'],
    'Idade': [28, 35, 22],
    'CPF': ['111.111.111-11', '222.222.222-22', '333.333.333-33'],
    'Telefone': ['(11) 9999-1111', '(21) 8888-2222', '(31) 7777-3333']
}
df_clientes = pd.DataFrame(dados_clientes)

print("DataFrame Original:")
display(df_clientes)

# Excluindo a coluna 'CPF' usando o comando del
del df_clientes['CPF']

# Excluindo a coluna 'Telefone' usando o método pop() em uma variável
coluna_telefone_removida = df_clientes.pop('Telefone')

# Exibindo o DataFrame resultante das exclusões
print("\nDataFrame após a remoção das colunas 'CPF' e 'Telefone':")
display(df_clientes)

# Exibindo o conteúdo da coluna que foi removida com pop()
print("\nConteúdo da coluna 'Telefone' que foi extraída com o pop():")
print(coluna_telefone_removida)

DataFrame Original:

      Nome  Idade             CPF        Telefone
0      Ana     28  111.111.111-11  (11) 9999-1111
1   Carlos     35  222.222.222-22  (21) 8888-2222
2  Beatriz     22  333.333.333-33  (31) 7777-3333

DataFrame após a remoção das colunas 'CPF' e 'Telefone':

      Nome  Idade
0      Ana     28
1   Carlos     35
2  Beatriz     22

Conteúdo da coluna 'Telefone' que foi extraída com o pop():
0    (11) 9999-1111
1    (21) 8888-2222
2    (31) 7777-3333
Name: Telefone, dtype: str

In [ ]:
# Questão 6

# Criando um DataFrame de exemplo com os países como índice
dados = {
    'População (milhões)': [214.3, 45.8, 19.5],
    'Capital': ['Brasília', 'Buenos Aires', 'Santiago'],
    'Idioma': ['Português', 'Espanhol', 'Espanhol']
}
indices = ['Brasil', 'Argentina', 'Chile']

df_paises = pd.DataFrame(dados, index=indices)

# Utilizando o método loc para recuperar os dados do Brasil
dados_brasil = df_paises.loc['Brasil']

# Imprimindo o resultado
print(dados_brasil)